export const conversationMarkdownSyntaxFixture = {
  markdown: [
    "# Heading level 1",
    "## Heading level 2",
    "### Heading level 3",
    "#### Heading level 4",
    "##### Heading level 5",
    "###### Heading level 6",
    "",
    "Paragraph line one",
    "paragraph line two with **strong asterisk**, __strong underscore__, *em asterisk*, _em underscore_, `inline code`, [absolute link](https://example.com/docs), [relative link](/chat), [anchor link](#section), and [mail link](mailto:team@example.com).",
    "",
    "![Embedded diagram](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII=)",
    "",
    "> Quoted line one",
    "> Quoted line two with `quoted code`.",
    "",
    "- Dash item",
    "* Star item",
    "+ Plus item with `list code`",
    "",
    "1. Ordered item one",
    "2. Ordered item two with **strong text**",
    "",
    "---",
    "***",
    "___",
    "",
    "```ts",
    "const ready = true;",
    "```",
    "",
    "```",
    "plain fenced code",
    "```",
    "",
    "| Syntax | Rendered |",
    "| --- | --- |",
    "| escaped pipe | A \\| B |",
    "| inline code | `table code` |",
    "",
    "Raw HTML stays text: <mark>not trusted</mark>",
  ].join("\n"),
  expected: {
    headings: [
      "Heading level 1",
      "Heading level 2",
      "Heading level 3",
      "Heading level 4",
      "Heading level 5",
      "Heading level 6",
    ],
    paragraphCount: 4,
    strongCount: 3,
    emphasisCount: 2,
    inlineCodeCount: 4,
    linkCount: 5,
    imageCount: 1,
    blockquoteCount: 1,
    unorderedListCount: 1,
    orderedListCount: 1,
    horizontalRuleCount: 3,
    codeBlockCount: 2,
    tableCount: 1,
  },
} as const;
