export const conversationMarkdownSyntaxFixture = {
  markdown: [
    "# H1 一级标题",
    "## H2 二级标题",
    "### H3 三级标题",
    "#### H4 四级标题",
    "##### H5 五级标题",
    "###### H6 六级标题",
    "",
    "Setext 一级标题",
    "===",
    "",
    "Setext 二级标题",
    "---",
    "",
    "普通段落文本。这里包含**加粗**、*斜体*、***加粗斜体***、~~删除线~~、`行内代码`、==高亮==、上标 x^2^、下标 H2O。  ",
    "这一行通过上一行末尾两个空格换行。",
    "",
    "> 这是一级引用。",
    ">",
    "> > 这是嵌套引用。",
    "> >",
    "> > 引用中也可以包含**加粗**、列表和代码：",
    "> > - 引用列表项",
    "> > - `quoted code`",
    "",
    "无序列表：",
    "",
    "- 项目 A",
    "- 项目 B",
    "  - 嵌套项目 B.1",
    "  - 嵌套项目 B.2",
    "    - 更深层项目",
    "- 项目 C",
    "",
    "有序列表：",
    "",
    "1. 第一步",
    "2. 第二步",
    "   1. 第二步的子步骤",
    "   2. 第二步的另一个子步骤",
    "3. 第三步",
    "",
    "任务列表：",
    "",
    "- [x] 已完成任务",
    "- [ ] 未完成任务",
    "- [x] 支持 **Markdown** 的任务项",
    "",
    "定义列表：",
    "",
    "术语 A",
    ":这是术语 A 的定义。",
    "",
    "术语 B",
    ":这是术语 B 的第一条定义。",
    ":这是术语 B 的第二条定义。",
    "",
    "表格：",
    "",
    "短字符表格：",
    "",
    "| 左 | 中 | 右 |",
    "| :--- | :---: | ---: |",
    "| A | B | C |",
    "| 1 | 2 | 3 |",
    "",
    "长中文表格：",
    "",
    "| 场景 | 说明 | 处理策略 |",
    "| --- | --- | --- |",
    "| 长句 | 这是一段较长的中文单元格内容，用于验证普通文本在消息正文中按可读宽度自然换行，而不是把表格强制撑出屏幕。 | 保持横向分割线，允许单元格内部按词句换行。 |",
    "| 多信息 | 包含状态、时间、路径和简短结论的组合说明，用于模拟真实回答里的摘要表格。 | 短内容不固定到额外像素宽度。 |",
    "",
    "长 URL 与代码表格：",
    "",
    "| 类型 | 内容 |",
    "| --- | --- |",
    "| 链接 | [长链接](https://example.com/docs/very/long/path?query=markdown-table-demo) |",
    "| API | `/api/terminal/sessions/abcd1234` |",
    "| 查询参数 | `session_id=abcd1234&markdown_demo=1` |",
    "",
    "混合内容表格：",
    "",
    "| Syntax | Rendered |",
    "| --- | --- |",
    "| escaped pipe | A \\| B |",
    "| inline code | `table code` |",
    "| linked value | [链接](https://example.com/docs) |",
    "",
    "链接：",
    "",
    "[行内链接](https://example.com/path)",
    "",
    "[带标题的链接](https://example.com/title \"Example title\")",
    "",
    "https://example.com",
    "",
    "test@example.com",
    "",
    "引用式链接：[OpenAI][openai-ref]",
    "",
    "[openai-ref]: https://openai.com",
    "",
    "图片：",
    "",
    "![Embedded diagram](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII=)",
    "",
    "带链接的图片：",
    "",
    "[![Linked pixel](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII=)](https://example.com/image)",
    "",
    "行内 HTML：",
    "",
    "这是一段 HTML span 文本：<span>不执行</span>。",
    "",
    "折叠内容：",
    "",
    "```html",
    "<details>",
    "<summary>点击展开</summary>",
    "```",
    "",
    "这里是折叠区域中的内容。",
    "",
    "- 可以放列表",
    "- 可以放 **加粗文本**",
    "- 可以放 `代码`",
    "",
    "```html",
    "</details>",
    "```",
    "",
    "行内代码示例：使用 `npm install package-name` 安装依赖。",
    "",
    "代码块：",
    "",
    "```js",
    "function hello(name) {",
    "  console.log(`Hello, ${name}!`);",
    "}",
    "",
    "hello(\"Markdown\");",
    "```",
    "",
    "水平分割线：",
    "",
    "---",
    "***",
    "___",
    "",
    "Emoji：",
    "",
    ":smile: :rocket: :white_check_mark:",
    "",
    "提及与标签：",
    "",
    "@username",
    "",
    "#markdown",
    "",
    "混合嵌套：",
    "",
    "1. **一级有序项**",
    "   - 无序子项",
    "   - 另一个无序子项，包含 [链接](https://example.com/nested)",
    "     > 子项中的引用",
    "     ```python",
    "     print(\"nested markdown\")",
    "     ```",
    "2. 第二个有序项",
    "",
    "完成。",
    "",
    "Raw HTML stays text: <mark>not trusted</mark>",
  ].join("\n"),
  expected: {
    headings: [
      "H1 一级标题",
      "H2 二级标题",
      "H3 三级标题",
      "H4 四级标题",
      "H5 五级标题",
      "H6 六级标题",
    ],
    paragraphCount: 41,
    strongCount: 6,
    emphasisCount: 2,
    inlineCodeCount: 7,
    linkCount: 10,
    imageCount: 2,
    blockquoteCount: 3,
    unorderedListCount: 7,
    orderedListCount: 3,
    horizontalRuleCount: 3,
    codeBlockCount: 4,
    tableCount: 4,
  },
} as const;
