package application

import controldomain "alter0/internal/control/domain"

func builtinAgents() []controldomain.Agent {
	return []controldomain.Agent{
		{
			ID:            "main",
			Name:          "Alter0",
			Type:          controldomain.CapabilityTypeAgent,
			Enabled:       true,
			Scope:         controldomain.CapabilityScopeGlobal,
			Version:       controldomain.DefaultCapabilityVersion,
			SystemPrompt:  "Act as alter0's primary assistant and orchestrator for an ongoing session. Understand the user's real goal, carry forward stable preferences and session context from memory, and turn that understanding into precise Codex CLI instructions. Delegate to specialist agents when that will improve quality or speed, including routing travel-planning work to the builtin travel agent when appropriate. Do not perform repository or shell work yourself; Codex CLI is the concrete executor. Keep the conversation cohesive and own the final answer.",
			MaxIterations: 12,
			Tools:         []string{"codex_exec", "delegate_agent", "search_memory", "read_memory", "write_memory"},
			Skills:        []string{"memory"},
			MemoryFiles:   []string{"user_md", "soul_md", "agents_md", "memory_long_term", "memory_daily_today"},
			SessionProfileFields: []controldomain.AgentSessionProfileField{
				{Key: "session_goal", Label: "Session Goal"},
				{Key: "active_workspace", Label: "Active Workspace", ReadOnly: true},
			},
			Source:       controldomain.AgentSourceBuiltin,
			Kind:         controldomain.AgentKindMain,
			Description:  "Default conversation entrypoint that can coordinate builtin and managed specialist agents.",
			EntryPoint:   true,
			UIRoute:      "chat",
			Capabilities: []string{"general", "orchestration", "travel-routing"},
		},
		{
			ID:            "coding",
			Name:          "Coding Agent",
			Type:          controldomain.CapabilityTypeAgent,
			Enabled:       true,
			Scope:         controldomain.CapabilityScopeGlobal,
			Version:       controldomain.DefaultCapabilityVersion,
			SystemPrompt:  "Act as alter0's dedicated coding assistant for an ongoing engineering session. Own the engineering conversation, understand the requested repository change, reuse stable preferences and session context from memory, and drive implementation by repeatedly calling codex_exec with precise Codex-facing instructions until the task is complete or clearly blocked. Do not perform repository or shell work yourself except reading approved memory files. codex_exec already carries structured runtime context for stable workspace and delivery facts, so keep each instruction focused on the concrete incremental action. Treat the session's dedicated repository workspace as a full clone with its own .git metadata, not a git worktree, and treat branch hygiene, test-page verification, preview deployment success, and PR readiness as first-class delivery requirements. Keep the test repository configuration aligned with production for model provider, Codex executable path, agent path, and other execution-critical settings, except session-scoped cache data. After preview deployment succeeds, ask whether the user wants to do manual testing before continuing. When the user asks for GitHub delivery, move straight from successful preview deployment to signed commit, push, gh PR creation, and merge.",
			MaxIterations: 24,
			Tools:         []string{"codex_exec", "search_memory", "read_memory", "write_memory", "deploy_test_service"},
			Skills:        []string{"memory", "deploy-test-service"},
			MemoryFiles:   []string{"user_md", "soul_md", "agents_md", "memory_long_term", "memory_daily_today"},
			SessionProfileFields: []controldomain.AgentSessionProfileField{
				{Key: "repository_path", Label: "Repository", ReadOnly: true},
				{Key: "source_repository_path", Label: "Source Repository Path", ReadOnly: true},
				{Key: "remote_repository", Label: "Remote Repository", ReadOnly: true},
				{Key: "branch", Label: "Branch", ReadOnly: true},
				{Key: "base_branch", Label: "Base Branch", ReadOnly: true},
				{Key: "preview_url", Label: "Preview URL", ReadOnly: true},
				{Key: "preview_subdomain", Label: "Preview Subdomain", ReadOnly: true},
			},
			Source:       controldomain.AgentSourceBuiltin,
			Kind:         controldomain.AgentKindSpecialist,
			Description:  "Dedicated coding agent that owns user interaction and uses Codex-driven implementation loops for repository changes.",
			EntryPoint:   true,
			Delegatable:  true,
			UIRoute:      "",
			Capabilities: []string{"coding"},
		},
		{
			ID:            "writing",
			Name:          "Writing Agent",
			Type:          controldomain.CapabilityTypeAgent,
			Enabled:       true,
			Scope:         controldomain.CapabilityScopeGlobal,
			Version:       controldomain.DefaultCapabilityVersion,
			SystemPrompt:  "Act as alter0's writing assistant for an ongoing session. Understand the requested audience, tone, and durable preferences from memory, then use codex_exec for the concrete drafting or editing work. Preserve important facts, keep terminology consistent with the product and repository, and do not perform ordinary file operations yourself.",
			MaxIterations: 12,
			Tools:         []string{"codex_exec", "search_memory", "read_memory", "write_memory"},
			Skills:        []string{"memory"},
			MemoryFiles:   []string{"user_md", "soul_md", "agents_md", "memory_long_term", "memory_daily_today"},
			SessionProfileFields: []controldomain.AgentSessionProfileField{
				{Key: "document_path", Label: "Document Path"},
				{Key: "audience", Label: "Audience"},
				{Key: "deliverable", Label: "Deliverable"},
			},
			Source:       controldomain.AgentSourceBuiltin,
			Kind:         controldomain.AgentKindSpecialist,
			Description:  "Specialist agent for product copy, documentation, and structured writing tasks.",
			EntryPoint:   true,
			Delegatable:  true,
			UIRoute:      "",
			Capabilities: []string{"writing"},
		},
		{
			ID:            controldomain.BuiltinTravelAgentID,
			Name:          "Travel Agent",
			Type:          controldomain.CapabilityTypeAgent,
			Enabled:       true,
			Scope:         controldomain.CapabilityScopeGlobal,
			Version:       controldomain.DefaultCapabilityVersion,
			SystemPrompt:  "Act as the single execution assistant for the travel product during an ongoing session. Understand the user's city-trip requirements, resolve durable preferences and shorthand from memory, directly synthesize city guide, route, metro, food, and map-oriented outputs within one coherent response model, preserve structured travel fields for later revisions, and drive all concrete generation through codex_exec. In addition to the normal conversational travel answer, produce a separate HTML travel guide artifact for the current request and publish it to the session's public read-only travel subdomain https://<session_short_hash>.travel.alter0.cn by using deploy_test_service with the travel service host. Treat that HTML guide as a first-class deliverable, keep it aligned with the conversational answer, and report the resulting URL in the final response. Keep the travel agent in the assistant role rather than performing file, shell, or repository work itself. Treat the agent-private file-backed `SKILL.md` as the canonical reusable rulebook for city page generation, and only update it when the user states a durable preference that should apply to future travel pages rather than one-off trip details.",
			MaxIterations: 12,
			Tools:         []string{"codex_exec", "search_memory", "read_memory", "write_memory", "deploy_test_service"},
			Skills:        []string{"memory", "deploy-test-service"},
			MemoryFiles:   []string{"user_md", "soul_md", "agents_md", "memory_long_term", "memory_daily_today"},
			SessionProfileFields: []controldomain.AgentSessionProfileField{
				{Key: "city", Label: "City"},
				{Key: "district", Label: "District"},
				{Key: "days", Label: "Days"},
				{Key: "hotel_area", Label: "Hotel Area"},
				{Key: "guide_html_url", Label: "Guide HTML URL"},
			},
			Source:       controldomain.AgentSourceBuiltin,
			Kind:         controldomain.AgentKindSpecialist,
			Description:  "Builtin specialist agent for travel planning, itinerary synthesis, and HTML guide delivery.",
			EntryPoint:   true,
			Delegatable:  true,
			UIRoute:      "",
			Capabilities: []string{"travel"},
		},
	}
}
