package application

import controldomain "alter0/internal/control/domain"

func builtinAgents() []controldomain.Agent {
	return []controldomain.Agent{
		{
			ID:            "main",
			Name:          "Alter0",
			Type:          controldomain.CapabilityTypeAgent,
			Enabled:       true,
			Scope:         controldomain.CapabilityScopeGlobal,
			Version:       controldomain.DefaultCapabilityVersion,
			SystemPrompt:  "Act as alter0's primary orchestrator. Clarify the user's real goal, complete direct work when it is straightforward, and delegate specialized product, coding, or writing work to the best specialist agent when that will improve quality or speed. When the user is asking for a product-domain task such as travel planning, route the execution to that product's master agent instead of handling every detail yourself. Keep the conversation cohesive and own the final answer.",
			MaxIterations: 8,
			Tools:         []string{"list_dir", "read", "write", "edit", "bash", "codex_exec", "delegate_agent"},
			Skills:        []string{"memory"},
			MemoryFiles:   []string{"user_md", "soul_md", "agents_md", "memory_long_term", "memory_daily_today"},
			Source:        controldomain.AgentSourceBuiltin,
			Kind:          controldomain.AgentKindMain,
			Description:   "Default conversation entrypoint that can coordinate specialist and product agents.",
			EntryPoint:    true,
			UIRoute:       "chat",
			Capabilities:  []string{"general", "orchestration", "product-routing"},
		},
		{
			ID:            "coding",
			Name:          "Coding Agent",
			Type:          controldomain.CapabilityTypeAgent,
			Enabled:       true,
			Scope:         controldomain.CapabilityScopeGlobal,
			Version:       controldomain.DefaultCapabilityVersion,
			SystemPrompt:  "Focus on engineering delivery. Inspect the repo, make the required code changes, run the most relevant verification you can, and report concise implementation outcomes with concrete file references.",
			MaxIterations: 10,
			Tools:         []string{"list_dir", "read", "write", "edit", "bash", "codex_exec"},
			Skills:        []string{"memory"},
			MemoryFiles:   []string{"user_md", "soul_md", "agents_md", "memory_long_term", "memory_daily_today"},
			Source:        controldomain.AgentSourceBuiltin,
			Kind:          controldomain.AgentKindSpecialist,
			Description:   "Specialist agent for repository analysis, implementation, and verification.",
			EntryPoint:    true,
			Delegatable:   true,
			UIRoute:       "",
			Capabilities:  []string{"coding"},
		},
		{
			ID:            "writing",
			Name:          "Writing Agent",
			Type:          controldomain.CapabilityTypeAgent,
			Enabled:       true,
			Scope:         controldomain.CapabilityScopeGlobal,
			Version:       controldomain.DefaultCapabilityVersion,
			SystemPrompt:  "Focus on writing and editing. Produce structured, polished drafts that match the requested audience, preserve important facts, and keep terminology consistent with the product and repository.",
			MaxIterations: 8,
			Tools:         []string{"list_dir", "read", "write", "edit", "bash"},
			Skills:        []string{"memory"},
			MemoryFiles:   []string{"user_md", "soul_md", "agents_md", "memory_long_term", "memory_daily_today"},
			Source:        controldomain.AgentSourceBuiltin,
			Kind:          controldomain.AgentKindSpecialist,
			Description:   "Specialist agent for product copy, documentation, and structured writing tasks.",
			EntryPoint:    true,
			Delegatable:   true,
			UIRoute:       "",
			Capabilities:  []string{"writing"},
		},
		{
			ID:            "product-builder",
			Name:          "Product Agent",
			Type:          controldomain.CapabilityTypeAgent,
			Enabled:       true,
			Scope:         controldomain.CapabilityScopeGlobal,
			Version:       controldomain.DefaultCapabilityVersion,
			SystemPrompt:  "Design and evolve product matrices. Define product scope, master agent responsibilities, worker-agent roles, artifact types, and implementation boundaries in a way that is execution-ready and maintainable.",
			MaxIterations: 8,
			Tools:         []string{"list_dir", "read", "write", "edit", "bash", "delegate_agent"},
			Skills:        []string{"memory"},
			MemoryFiles:   []string{"user_md", "soul_md", "agents_md", "memory_long_term", "memory_daily_today"},
			Source:        controldomain.AgentSourceBuiltin,
			Kind:          controldomain.AgentKindSpecialist,
			Description:   "Specialist product agent for defining products, master agents, and worker-agent matrices.",
			Delegatable:   true,
			UIRoute:       "",
			Capabilities:  []string{"product-design", "agent-matrix"},
		},
		{
			ID:            "travel-master",
			Name:          "Travel Master Agent",
			Type:          controldomain.CapabilityTypeAgent,
			Enabled:       true,
			Scope:         controldomain.CapabilityScopeGlobal,
			Version:       controldomain.DefaultCapabilityVersion,
			SystemPrompt:  "Act as the master agent for the travel product. Understand the user's city-trip requirements, break work into city guide, route, metro, food, and map subtasks when helpful, preserve structured travel fields for later revisions, and return a coherent travel plan.",
			MaxIterations: 8,
			Tools:         []string{"delegate_agent", "complete"},
			Skills:        []string{"memory"},
			MemoryFiles:   []string{"user_md", "soul_md", "agents_md", "memory_long_term", "memory_daily_today"},
			Source:        controldomain.AgentSourceBuiltin,
			Kind:          controldomain.AgentKindSpecialist,
			Description:   "Product master agent for travel planning, itinerary synthesis, and travel guide revisions.",
			Delegatable:   true,
			UIRoute:       "",
			Capabilities:  []string{"travel", "product-master"},
		},
		{
			ID:            "travel-city-guide",
			Name:          "Travel City Guide Agent",
			Type:          controldomain.CapabilityTypeAgent,
			Enabled:       true,
			Scope:         controldomain.CapabilityScopeGlobal,
			Version:       controldomain.DefaultCapabilityVersion,
			SystemPrompt:  "Specialize in city-level travel guidance. Organize scenic spots, neighborhoods, visit durations, and city overview details for the target trip.",
			MaxIterations: 6,
			Tools:         []string{"complete"},
			Source:        controldomain.AgentSourceBuiltin,
			Kind:          controldomain.AgentKindSpecialist,
			Description:   "Travel worker agent for city overview, scenic spots, and attraction grouping.",
			Delegatable:   true,
			Capabilities:  []string{"travel", "city-guide"},
		},
		{
			ID:            "travel-route-planner",
			Name:          "Travel Route Planner Agent",
			Type:          controldomain.CapabilityTypeAgent,
			Enabled:       true,
			Scope:         controldomain.CapabilityScopeGlobal,
			Version:       controldomain.DefaultCapabilityVersion,
			SystemPrompt:  "Specialize in sequencing trip activities into day-by-day routes with realistic pacing and visit ordering.",
			MaxIterations: 6,
			Tools:         []string{"complete"},
			Source:        controldomain.AgentSourceBuiltin,
			Kind:          controldomain.AgentKindSpecialist,
			Description:   "Travel worker agent for day plans, route ordering, and pacing.",
			Delegatable:   true,
			Capabilities:  []string{"travel", "route-planning"},
		},
		{
			ID:            "travel-metro-guide",
			Name:          "Travel Metro Guide Agent",
			Type:          controldomain.CapabilityTypeAgent,
			Enabled:       true,
			Scope:         controldomain.CapabilityScopeGlobal,
			Version:       controldomain.DefaultCapabilityVersion,
			SystemPrompt:  "Specialize in metro and public-transit guidance for city trips. Explain how to move between stops and when transit is preferable.",
			MaxIterations: 6,
			Tools:         []string{"complete"},
			Source:        controldomain.AgentSourceBuiltin,
			Kind:          controldomain.AgentKindSpecialist,
			Description:   "Travel worker agent for metro lines, station suggestions, and transit advice.",
			Delegatable:   true,
			Capabilities:  []string{"travel", "metro"},
		},
		{
			ID:            "travel-food-recommender",
			Name:          "Travel Food Recommender Agent",
			Type:          controldomain.CapabilityTypeAgent,
			Enabled:       true,
			Scope:         controldomain.CapabilityScopeGlobal,
			Version:       controldomain.DefaultCapabilityVersion,
			SystemPrompt:  "Specialize in recommending food and dining choices that match the route, time of day, and user preferences.",
			MaxIterations: 6,
			Tools:         []string{"complete"},
			Source:        controldomain.AgentSourceBuiltin,
			Kind:          controldomain.AgentKindSpecialist,
			Description:   "Travel worker agent for dining recommendations and food planning.",
			Delegatable:   true,
			Capabilities:  []string{"travel", "food"},
		},
		{
			ID:            "travel-map-annotator",
			Name:          "Travel Map Annotator Agent",
			Type:          controldomain.CapabilityTypeAgent,
			Enabled:       true,
			Scope:         controldomain.CapabilityScopeGlobal,
			Version:       controldomain.DefaultCapabilityVersion,
			SystemPrompt:  "Specialize in map expression for travel products. Prepare point, line, and layer descriptions for routes, scenic spots, food stops, and transit hops.",
			MaxIterations: 6,
			Tools:         []string{"complete"},
			Source:        controldomain.AgentSourceBuiltin,
			Kind:          controldomain.AgentKindSpecialist,
			Description:   "Travel worker agent for map-oriented route and layer annotations.",
			Delegatable:   true,
			Capabilities:  []string{"travel", "map"},
		},
	}
}
