package application

import controldomain "alter0/internal/control/domain"

func builtinAgents() []controldomain.Agent {
	return []controldomain.Agent{
		{
			ID:            "main",
			Name:          "Alter0",
			Type:          controldomain.CapabilityTypeAgent,
			Enabled:       true,
			Scope:         controldomain.CapabilityScopeGlobal,
			Version:       controldomain.DefaultCapabilityVersion,
			SystemPrompt:  "Act as alter0's primary orchestrator. Clarify the user's real goal, complete direct work when it is straightforward, and delegate specialized coding or writing work to the best specialist agent when that will improve quality or speed. Keep the conversation cohesive and own the final answer.",
			MaxIterations: 8,
			Tools:         []string{"list_dir", "read", "write", "edit", "bash", "codex_exec", "delegate_agent"},
			Skills:        []string{"memory"},
			MemoryFiles:   []string{"user_md", "soul_md", "agents_md", "memory_long_term", "memory_daily_today"},
			Source:        controldomain.AgentSourceBuiltin,
			Kind:          controldomain.AgentKindMain,
			Description:   "Default conversation entrypoint that can coordinate specialist agents.",
			EntryPoint:    true,
			UIRoute:       "chat",
			Capabilities:  []string{"general", "orchestration"},
		},
		{
			ID:            "coding",
			Name:          "Coding Agent",
			Type:          controldomain.CapabilityTypeAgent,
			Enabled:       true,
			Scope:         controldomain.CapabilityScopeGlobal,
			Version:       controldomain.DefaultCapabilityVersion,
			SystemPrompt:  "Focus on engineering delivery. Inspect the repo, make the required code changes, run the most relevant verification you can, and report concise implementation outcomes with concrete file references.",
			MaxIterations: 10,
			Tools:         []string{"list_dir", "read", "write", "edit", "bash", "codex_exec"},
			Skills:        []string{"memory"},
			MemoryFiles:   []string{"user_md", "soul_md", "agents_md", "memory_long_term", "memory_daily_today"},
			Source:        controldomain.AgentSourceBuiltin,
			Kind:          controldomain.AgentKindSpecialist,
			Description:   "Specialist agent for repository analysis, implementation, and verification.",
			EntryPoint:    true,
			Delegatable:   true,
			UIRoute:       "coding",
			Capabilities:  []string{"coding"},
		},
		{
			ID:            "writing",
			Name:          "Writing Agent",
			Type:          controldomain.CapabilityTypeAgent,
			Enabled:       true,
			Scope:         controldomain.CapabilityScopeGlobal,
			Version:       controldomain.DefaultCapabilityVersion,
			SystemPrompt:  "Focus on writing and editing. Produce structured, polished drafts that match the requested audience, preserve important facts, and keep terminology consistent with the product and repository.",
			MaxIterations: 8,
			Tools:         []string{"list_dir", "read", "write", "edit", "bash"},
			Skills:        []string{"memory"},
			MemoryFiles:   []string{"user_md", "soul_md", "agents_md", "memory_long_term", "memory_daily_today"},
			Source:        controldomain.AgentSourceBuiltin,
			Kind:          controldomain.AgentKindSpecialist,
			Description:   "Specialist agent for product copy, documentation, and structured writing tasks.",
			EntryPoint:    true,
			Delegatable:   true,
			UIRoute:       "writing",
			Capabilities:  []string{"writing"},
		},
	}
}
