package application

import controldomain "alter0/internal/control/domain"

func defaultEnvironmentDefinitions() []controldomain.EnvironmentDefinition {
	return []controldomain.EnvironmentDefinition{
		{
			Key:          "web_addr",
			Name:         "Web Listen Address",
			Module:       "Web & Queue",
			Description:  "控制 HTTP 服务监听的 host:port。浏览器和反向代理都会连接到这里，修改后需要同步更新访问地址或上游配置，并在重启后生效。",
			Type:         controldomain.EnvironmentValueTypeString,
			DefaultValue: "127.0.0.1:18088",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
			},
		},
		{
			Key:          "web_bind_localhost_only",
			Name:         "Web Bind Loopback Only",
			Module:       "Web & Queue",
			Description:  "控制是否强制仅监听本机回环地址。开启后服务只接受本机或本机反向代理访问，更适合单机部署；关闭后才允许直接暴露到外部网卡地址。",
			Type:         controldomain.EnvironmentValueTypeEnum,
			DefaultValue: "true",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Allowed:  []string{"true", "false"},
			},
		},
		{
			Key:          "web_login_password",
			Name:         "Web Login Password",
			Module:       "Web & Queue",
			Description:  "Web 控制台登录密码。所有进入控制台与受保护预览工作区的用户都必须先通过该密码验证；静态只读公开 host 不受此项约束。",
			Type:         controldomain.EnvironmentValueTypeString,
			DefaultValue: "",
			Sensitive:    true,
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: false,
			},
		},
		{
			Key:          "worker_pool_size",
			Name:         "Worker Pool Size",
			Module:       "Web & Queue",
			Description:  "全局共享工作池并发数，影响请求处理、后台调度等共享工作负载的吞吐能力。数值越大并发越高，但也会增加 CPU 与内存占用。",
			Type:         controldomain.EnvironmentValueTypeInteger,
			DefaultValue: "4",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "1",
				Max:      "64",
			},
		},
		{
			Key:          "max_queue_size",
			Name:         "Max Queue Size",
			Module:       "Web & Queue",
			Description:  "当工作池繁忙时允许排队的最大请求/任务数量。值过小会更早拒绝高峰流量，值过大则会增加等待时延和内存占用。",
			Type:         controldomain.EnvironmentValueTypeInteger,
			DefaultValue: "128",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "1",
				Max:      "8192",
			},
		},
		{
			Key:          "queue_timeout",
			Name:         "Queue Timeout",
			Module:       "Web & Queue",
			Description:  "请求或任务在等待队列中允许停留的最长时间。超过该时间后会超时返回，用于避免高峰期出现无限排队。",
			Type:         controldomain.EnvironmentValueTypeDuration,
			DefaultValue: "5s",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "100ms",
				Max:      "30m",
			},
		},
		{
			Key:          "async_task_workers",
			Name:         "Async Task Workers",
			Module:       "Async Tasks",
			Description:  "异步任务执行器的并发 worker 数，决定后台最多可同时处理多少异步任务。提高后可提升吞吐，但会与前台请求争抢资源。",
			Type:         controldomain.EnvironmentValueTypeInteger,
			DefaultValue: "5",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "1",
				Max:      "5",
			},
		},
		{
			Key:          "async_task_timeout",
			Name:         "Async Task Timeout",
			Module:       "Async Tasks",
			Description:  "单个异步任务一次执行允许持续的最长时间。超过后任务会被中断或标记失败，用于防止后台任务长期卡住。",
			Type:         controldomain.EnvironmentValueTypeDuration,
			DefaultValue: "90s",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "1s",
				Max:      "4h",
			},
		},
		{
			Key:          "async_task_max_retries",
			Name:         "Async Task Max Retries",
			Module:       "Async Tasks",
			Description:  "异步任务失败后的最大重试次数，不包含首次执行。适合处理瞬时故障，值越高越容易恢复，但总完成时间也会更长。",
			Type:         controldomain.EnvironmentValueTypeInteger,
			DefaultValue: "1",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "0",
				Max:      "10",
			},
		},
		{
			Key:          "async_task_trigger_threshold",
			Name:         "Async Task Trigger Threshold",
			Module:       "Async Tasks",
			Description:  "系统预测一次请求耗时达到该阈值时，会更倾向转入异步执行而不是阻塞当前交互，用于把长耗时任务从前台链路中分流出去。",
			Type:         controldomain.EnvironmentValueTypeDuration,
			DefaultValue: "5m",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "10s",
				Max:      "24h",
			},
		},
		{
			Key:          "async_long_content_threshold",
			Name:         "Async Long Content Threshold",
			Module:       "Async Tasks",
			Description:  "当输入内容或上下文长度超过该阈值时，系统会更积极地采用异步任务路径，减少长文本请求对实时响应的影响。",
			Type:         controldomain.EnvironmentValueTypeInteger,
			DefaultValue: "240",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "1",
				Max:      "20000",
			},
		},
		{
			Key:          "task_terminal_shell",
			Name:         "Terminal Shell",
			Module:       "Terminal",
			Description:  "终端会话启动子进程时使用的 shell 可执行文件或命令。留空时使用系统默认 shell；配置错误会导致终端页无法创建会话。",
			Type:         controldomain.EnvironmentValueTypeString,
			DefaultValue: "",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: false,
			},
		},
		{
			Key:          "session_memory_turns",
			Name:         "Session Memory Turns",
			Module:       "Session Memory",
			Description:  "单个会话短期记忆保留的最近对话轮数上限。值越大，上下文连续性更强，但提示词长度和成本也会随之增加。",
			Type:         controldomain.EnvironmentValueTypeInteger,
			DefaultValue: "6",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "1",
				Max:      "64",
			},
		},
		{
			Key:          "session_memory_ttl",
			Name:         "Session Memory TTL",
			Module:       "Session Memory",
			Description:  "短期会话记忆在无活动状态下的保留时长。超过后会过期清理，用于避免陈旧上下文长期污染后续对话。",
			Type:         controldomain.EnvironmentValueTypeDuration,
			DefaultValue: "20m",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "1m",
				Max:      "48h",
			},
		},
		{
			Key:          "context_compression_threshold",
			Name:         "Context Compression Threshold",
			Module:       "Session Memory",
			Description:  "预计上下文 token 累积超过该阈值时开始触发压缩。它控制压缩发生的时机，直接影响上下文窗口占用和摘要频率。",
			Type:         controldomain.EnvironmentValueTypeInteger,
			DefaultValue: "1200",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "128",
				Max:      "200000",
			},
		},
		{
			Key:          "context_compression_summary_tokens",
			Name:         "Compression Summary Tokens",
			Module:       "Session Memory",
			Description:  "每次压缩生成摘要时可使用的 token 预算上限。预算越大摘要越完整，但也会挤占后续请求可用的上下文额度。",
			Type:         controldomain.EnvironmentValueTypeInteger,
			DefaultValue: "220",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "32",
				Max:      "4000",
			},
		},
		{
			Key:          "context_compression_retain_turns",
			Name:         "Compression Retain Turns",
			Module:       "Session Memory",
			Description:  "执行上下文压缩时强制保留的最近原始轮数。用于确保最新对话仍以原文形式存在，不会被摘要完全替代。",
			Type:         controldomain.EnvironmentValueTypeInteger,
			DefaultValue: "4",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "1",
				Max:      "24",
			},
		},
		{
			Key:          "daily_memory_dir",
			Name:         "Daily Memory Directory",
			Module:       "Persistent Memory",
			Description:  "每日记忆文件与索引的写入目录。修改后会改变持久化落盘位置，需要同时确认目录存在、权限正确并纳入备份策略。",
			Type:         controldomain.EnvironmentValueTypeString,
			DefaultValue: ".alter0/memory",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
			},
		},
		{
			Key:          "long_term_memory_path",
			Name:         "Long-Term Memory Path",
			Module:       "Persistent Memory",
			Description:  "长期记忆主文件路径。系统会从这里读取和更新长期知识，修改时需要确保父目录存在且运行进程具备写权限。",
			Type:         controldomain.EnvironmentValueTypeString,
			DefaultValue: ".alter0/memory/long-term/MEMORY.md",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
			},
		},
		{
			Key:          "long_term_memory_write_policy",
			Name:         "Long-Term Memory Write Policy",
			Module:       "Persistent Memory",
			Description:  "控制长期记忆采用同步写入还是缓冲后回写。`write_through` 更安全、写后即落盘；`write_back` I/O 更省，但在刷盘前存在短暂丢失风险。",
			Type:         controldomain.EnvironmentValueTypeEnum,
			DefaultValue: "write_through",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Allowed:  []string{"write_through", "write_back"},
			},
		},
		{
			Key:          "long_term_memory_writeback_flush",
			Name:         "Write-Back Flush Interval",
			Module:       "Persistent Memory",
			Description:  "在 `write_back` 模式下，内存缓冲内容刷盘到长期记忆文件的时间间隔。间隔越短越安全，间隔越长越节省磁盘 I/O。",
			Type:         controldomain.EnvironmentValueTypeDuration,
			DefaultValue: "2s",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "500ms",
				Max:      "30m",
			},
		},
		{
			Key:          "long_term_memory_token_budget",
			Name:         "Long-Term Memory Token Budget",
			Module:       "Persistent Memory",
			Description:  "长期记忆在请求时注入到模型上下文中的 token 预算上限。值越大可召回更多长期知识，但会压缩模型用于当前任务的上下文空间。",
			Type:         controldomain.EnvironmentValueTypeInteger,
			DefaultValue: "220",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "32",
				Max:      "8000",
			},
		},
		{
			Key:          "mandatory_context_file",
			Name:         "Mandatory Context File",
			Module:       "Persistent Memory",
			Description:  "每次请求都会强制注入的上下文文件路径，适合放系统约束、角色设定或团队固定规则。文件越大，对上下文窗口占用越明显。",
			Type:         controldomain.EnvironmentValueTypeString,
			DefaultValue: "SOUL.md",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
			},
		},
		// LLM Configuration
		{
			Key:          "llm_temperature",
			Name:         "Temperature",
			Module:       "LLM",
			Description:  "控制模型采样温度。值越低，输出越稳定和保守；值越高，输出越发散和多样。具体可用范围仍取决于所选 provider 与模型。",
			Type:         controldomain.EnvironmentValueTypeString,
			DefaultValue: "0.7",
			ApplyMode:    controldomain.EnvironmentApplyModeImmediate,
			Validation: controldomain.EnvironmentValidation{
				Required: false,
			},
		},
		{
			Key:          "llm_max_tokens",
			Name:         "Max Tokens",
			Module:       "LLM",
			Description:  "单次响应允许生成的最大 token 数。调大后可返回更长内容，但也会提高响应时延、成本以及触达上下文上限的概率。",
			Type:         controldomain.EnvironmentValueTypeInteger,
			DefaultValue: "4096",
			ApplyMode:    controldomain.EnvironmentApplyModeImmediate,
			Validation: controldomain.EnvironmentValidation{
				Required: false,
				Min:      "1",
				Max:      "1000000",
			},
		},
		{
			Key:          "llm_react_max_iterations",
			Name:         "ReAct Max Iterations",
			Module:       "LLM",
			Description:  "ReAct Agent 在一次任务中允许执行的“思考/行动”迭代上限。该值用于限制复杂任务的循环深度、工具调用次数和整体成本。",
			Type:         controldomain.EnvironmentValueTypeInteger,
			DefaultValue: "10",
			ApplyMode:    controldomain.EnvironmentApplyModeImmediate,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "1",
				Max:      "100",
			},
		},
	}
}
