package application

import controldomain "alter0/internal/control/domain"

func defaultEnvironmentDefinitions() []controldomain.EnvironmentDefinition {
	return []controldomain.EnvironmentDefinition{
		{
			Key:          "web_addr",
			Name:         "Web Listen Address",
			Module:       "Web & Queue",
			Description:  "Web 服务监听地址",
			Type:         controldomain.EnvironmentValueTypeString,
			DefaultValue: "127.0.0.1:18088",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
			},
		},
		{
			Key:          "web_bind_localhost_only",
			Name:         "Web Bind Loopback Only",
			Module:       "Web & Queue",
			Description:  "是否强制仅监听本机回环地址（建议 Nginx 反向代理时开启）",
			Type:         controldomain.EnvironmentValueTypeEnum,
			DefaultValue: "true",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Allowed:  []string{"true", "false"},
			},
		},
		{
			Key:          "web_login_password",
			Name:         "Web Login Password",
			Module:       "Web & Queue",
			Description:  "Web 登录密码（留空表示关闭登录页面）",
			Type:         controldomain.EnvironmentValueTypeString,
			DefaultValue: "",
			Sensitive:    true,
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: false,
			},
		},
		{
			Key:          "worker_pool_size",
			Name:         "Worker Pool Size",
			Module:       "Web & Queue",
			Description:  "全局并发工作线程数量",
			Type:         controldomain.EnvironmentValueTypeInteger,
			DefaultValue: "4",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "1",
				Max:      "64",
			},
		},
		{
			Key:          "max_queue_size",
			Name:         "Max Queue Size",
			Module:       "Web & Queue",
			Description:  "等待队列最大长度",
			Type:         controldomain.EnvironmentValueTypeInteger,
			DefaultValue: "128",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "1",
				Max:      "8192",
			},
		},
		{
			Key:          "queue_timeout",
			Name:         "Queue Timeout",
			Module:       "Web & Queue",
			Description:  "请求排队超时时间",
			Type:         controldomain.EnvironmentValueTypeDuration,
			DefaultValue: "5s",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "100ms",
				Max:      "30m",
			},
		},
		{
			Key:          "async_task_workers",
			Name:         "Async Task Workers",
			Module:       "Async Tasks",
			Description:  "异步任务执行并发度",
			Type:         controldomain.EnvironmentValueTypeInteger,
			DefaultValue: "5",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "1",
				Max:      "5",
			},
		},
		{
			Key:          "async_task_timeout",
			Name:         "Async Task Timeout",
			Module:       "Async Tasks",
			Description:  "异步任务单次执行超时时间",
			Type:         controldomain.EnvironmentValueTypeDuration,
			DefaultValue: "90s",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "1s",
				Max:      "4h",
			},
		},
		{
			Key:          "async_task_max_retries",
			Name:         "Async Task Max Retries",
			Module:       "Async Tasks",
			Description:  "异步任务最大重试次数",
			Type:         controldomain.EnvironmentValueTypeInteger,
			DefaultValue: "1",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "0",
				Max:      "10",
			},
		},
		{
			Key:          "async_task_trigger_threshold",
			Name:         "Async Task Trigger Threshold",
			Module:       "Async Tasks",
			Description:  "异步任务分流的预计耗时阈值",
			Type:         controldomain.EnvironmentValueTypeDuration,
			DefaultValue: "5m",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "10s",
				Max:      "24h",
			},
		},
		{
			Key:          "async_long_content_threshold",
			Name:         "Async Long Content Threshold",
			Module:       "Async Tasks",
			Description:  "触发异步分流的内容长度阈值",
			Type:         controldomain.EnvironmentValueTypeInteger,
			DefaultValue: "240",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "1",
				Max:      "20000",
			},
		},
		{
			Key:          "task_terminal_max_sessions",
			Name:         "Terminal Max Sessions",
			Module:       "Terminal",
			Description:  "终端会话最大并发数",
			Type:         controldomain.EnvironmentValueTypeInteger,
			DefaultValue: "5",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "1",
				Max:      "5",
			},
		},
		{
			Key:          "task_terminal_shell",
			Name:         "Terminal Shell",
			Module:       "Terminal",
			Description:  "终端会话使用的 shell；Windows 下已知 shell 会自动启用 UTF-8 启动逻辑",
			Type:         controldomain.EnvironmentValueTypeString,
			DefaultValue: "",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: false,
			},
		},
		{
			Key:          "session_memory_turns",
			Name:         "Session Memory Turns",
			Module:       "Session Memory",
			Description:  "短期会话记忆窗口轮数",
			Type:         controldomain.EnvironmentValueTypeInteger,
			DefaultValue: "6",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "1",
				Max:      "64",
			},
		},
		{
			Key:          "session_memory_ttl",
			Name:         "Session Memory TTL",
			Module:       "Session Memory",
			Description:  "短期会话记忆保留时长",
			Type:         controldomain.EnvironmentValueTypeDuration,
			DefaultValue: "20m",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "1m",
				Max:      "48h",
			},
		},
		{
			Key:          "context_compression_threshold",
			Name:         "Context Compression Threshold",
			Module:       "Session Memory",
			Description:  "触发上下文压缩的 token 阈值",
			Type:         controldomain.EnvironmentValueTypeInteger,
			DefaultValue: "1200",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "128",
				Max:      "200000",
			},
		},
		{
			Key:          "context_compression_summary_tokens",
			Name:         "Compression Summary Tokens",
			Module:       "Session Memory",
			Description:  "单段压缩摘要 token 预算",
			Type:         controldomain.EnvironmentValueTypeInteger,
			DefaultValue: "220",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "32",
				Max:      "4000",
			},
		},
		{
			Key:          "context_compression_retain_turns",
			Name:         "Compression Retain Turns",
			Module:       "Session Memory",
			Description:  "压缩时保留最近轮数",
			Type:         controldomain.EnvironmentValueTypeInteger,
			DefaultValue: "4",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "1",
				Max:      "24",
			},
		},
		{
			Key:          "daily_memory_dir",
			Name:         "Daily Memory Directory",
			Module:       "Persistent Memory",
			Description:  "每日记忆目录",
			Type:         controldomain.EnvironmentValueTypeString,
			DefaultValue: ".alter0/memory",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
			},
		},
		{
			Key:          "long_term_memory_path",
			Name:         "Long-Term Memory Path",
			Module:       "Persistent Memory",
			Description:  "长期记忆文件路径",
			Type:         controldomain.EnvironmentValueTypeString,
			DefaultValue: ".alter0/memory/long-term/MEMORY.md",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
			},
		},
		{
			Key:          "long_term_memory_write_policy",
			Name:         "Long-Term Memory Write Policy",
			Module:       "Persistent Memory",
			Description:  "长期记忆写入策略",
			Type:         controldomain.EnvironmentValueTypeEnum,
			DefaultValue: "write_through",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Allowed:  []string{"write_through", "write_back"},
			},
		},
		{
			Key:          "long_term_memory_writeback_flush",
			Name:         "Write-Back Flush Interval",
			Module:       "Persistent Memory",
			Description:  "长期记忆回写刷新间隔",
			Type:         controldomain.EnvironmentValueTypeDuration,
			DefaultValue: "2s",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "500ms",
				Max:      "30m",
			},
		},
		{
			Key:          "long_term_memory_token_budget",
			Name:         "Long-Term Memory Token Budget",
			Module:       "Persistent Memory",
			Description:  "长期记忆注入 token 预算",
			Type:         controldomain.EnvironmentValueTypeInteger,
			DefaultValue: "220",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
				Min:      "32",
				Max:      "8000",
			},
		},
		{
			Key:          "mandatory_context_file",
			Name:         "Mandatory Context File",
			Module:       "Persistent Memory",
			Description:  "强制注入上下文文件路径",
			Type:         controldomain.EnvironmentValueTypeString,
			DefaultValue: "SOUL.md",
			ApplyMode:    controldomain.EnvironmentApplyModeRestart,
			Validation: controldomain.EnvironmentValidation{
				Required: true,
			},
		},
	}
}
