#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export GOTOOLCHAIN="${GOTOOLCHAIN:-auto}"
export GOSUMDB="${GOSUMDB:-sum.golang.org}"

THRESHOLD_HISTORY_OUTPUT_PATH="${THRESHOLD_HISTORY_OUTPUT_PATH:-output/cost/threshold-history-latest.json}"
THRESHOLD_HISTORY_ARCHIVE_ROOT="${THRESHOLD_HISTORY_ARCHIVE_ROOT:-output/cost/threshold-history}"
ORCHESTRATOR_LOG_BASE="${ORCHESTRATOR_LOG_BASE:-output/orchestrator}"
THRESHOLD_HISTORY_WINDOW_HOURS="${THRESHOLD_HISTORY_WINDOW_HOURS:-168}"
THRESHOLD_HISTORY_ACTIVE_WINDOW_MINUTES="${THRESHOLD_HISTORY_ACTIVE_WINDOW_MINUTES:-30}"
THRESHOLD_HISTORY_SHARE_THRESHOLD="${THRESHOLD_HISTORY_SHARE_THRESHOLD:-0.35}"
THRESHOLD_HISTORY_PROMPT_RATIO_THRESHOLD="${THRESHOLD_HISTORY_PROMPT_RATIO_THRESHOLD:-6.0}"
THRESHOLD_HISTORY_MIN_TOKENS="${THRESHOLD_HISTORY_MIN_TOKENS:-1200}"
THRESHOLD_HISTORY_MAX_SAMPLES="${THRESHOLD_HISTORY_MAX_SAMPLES:-12}"

cd "$ROOT_DIR"

go run ./app/cmd/cost-threshold-history \
  --output "$THRESHOLD_HISTORY_OUTPUT_PATH" \
  --archive-root "$THRESHOLD_HISTORY_ARCHIVE_ROOT" \
  --orchestrator-log-base "$ORCHESTRATOR_LOG_BASE" \
  --window-hours "$THRESHOLD_HISTORY_WINDOW_HOURS" \
  --active-window-minutes "$THRESHOLD_HISTORY_ACTIVE_WINDOW_MINUTES" \
  --share-threshold "$THRESHOLD_HISTORY_SHARE_THRESHOLD" \
  --prompt-ratio-threshold "$THRESHOLD_HISTORY_PROMPT_RATIO_THRESHOLD" \
  --min-tokens "$THRESHOLD_HISTORY_MIN_TOKENS" \
  --max-samples "$THRESHOLD_HISTORY_MAX_SAMPLES"

echo "cost threshold history checks passed"
