package domain

const (
	ExecutionEngineMetadataKey           = "alter0.execution.engine"
	ExecutionSourceMetadataKey           = "alter0.execution.source"
	LLMProviderIDMetadataKey             = "alter0.llm.provider_id"
	LLMModelMetadataKey                  = "alter0.llm.model"
	AgentIDMetadataKey                   = "alter0.agent.id"
	AgentNameMetadataKey                 = "alter0.agent.name"
	AgentInstanceAttributesMetadataKey   = "alter0.agent.instance_attributes"
	AgentInstanceAttributeMetadataPrefix = "alter0.agent.instance_attr."
	AgentProviderIDMetadataKey           = "alter0.agent.provider_id"
	AgentModelMetadataKey                = "alter0.agent.model"
	AgentSystemPromptMetadataKey         = "alter0.agent.system_prompt"
	AgentMaxIterationsMetadataKey        = "alter0.agent.max_iterations"
	AgentToolsMetadataKey                = "alter0.agent.tools"
	AgentProcessStepsMetadataKey         = "alter0.agent.process_steps"
	AgentCapabilitiesMetadataKey         = "alter0.agent.capabilities"
	AgentDeliverablesMetadataKey         = "alter0.agent.deliverables"
	AgentCompletionChecksMetadataKey     = "alter0.agent.completion_checks"
	AgentDelegatedByMetadataKey          = "alter0.agent.delegated_by"
	AgentDelegationDepthMetadataKey      = "alter0.agent.delegation_depth"
	CodexRuntimeStrategyMetadataKey      = "alter0.codex.runtime_strategy"
	ClaudeAPIKeyMetadataKey              = "alter0.claude.api_key"
	ClaudeBaseURLMetadataKey             = "alter0.claude.base_url"
	ClaudeConfigDirMetadataKey           = "alter0.claude.config_dir"

	ExecutionEngineAuto   = "auto"
	ExecutionEngineCodex  = "codex"
	ExecutionEngineClaude = "claude"
	ExecutionEngineReact  = "react"
	ExecutionEngineAgent  = "agent"

	ExecutionSourceModel      = "model"
	ExecutionSourceClaudeCode = "claude_code"
	ExecutionSourceCodexCLI   = "codex_cli"

	CodexRuntimeStrategyNative = "native"
	CodexRuntimeStrategyPlain  = "plain"
)
